// Boss-owned: production manager delivery closure and late-response boundaries.
import {it,expect,vi} from 'vitest';
import {ConversationManager} from '../src/conversation-manager.js';
function fixture(action: 'chat'|'observe'='chat'){
 const messages:any[]=[];let publish:(e:any)=>void=()=>{};let streaming=false;let answer:(text:string)=>void=()=>{};
 const compose=vi.fn(()=>new Promise<string>(resolve=>{answer=resolve;}));
 const manager=new ConversationManager(async(_id,emit)=>{
  publish=e=>{if(e.kind==='agent_start')streaming=true;if(e.kind==='agent_end'||e.kind==='error')streaming=false;emit({type:'agent_event',event:e});};
  return {session:{available:true,modelName:()=> 'test',isStreaming:()=>streaming,isHeld:()=>false,startTask:()=>publish({kind:'agent_start',deliveryMode:'explicit'}),classifyVoiceInput:async(text:string)=>({steps:[{action,text,target:null}]}),answerVoiceObservation:async()=> '当前页面有竹海工作坊活动邀请，正文尚未打开。',composeUserDelivery:compose,abort:()=>{streaming=false;}},fleet:{teamView:()=>null,isGroupHeld:()=>false,abortTeam:()=>{},reset:()=>{}},rpc:{rejectAll:()=>{},call:async()=>({tabId:1,url:'https://fixture.test',title:'收件箱',text:'竹海工作坊活动邀请',imageBase64:'AQ==',documentId:'doc-one',capturedAt:100,scope:'viewport'})},handleMessage:(m:any)=>{if(m.type==='user_message')publish({kind:'agent_start'});},dispose:()=>{}} as any;
 },m=>messages.push(m));
 return {manager,messages,compose,event:(e:any)=>publish(e),resolve:(text:string)=>answer(text)};
}
const raw='竹海工作坊的活动邀请，只看过标题，没有读正文。';
async function start(h:ReturnType<typeof fixture>){await h.manager.ensureDefault();await h.manager.handleMessage({type:'user_message',conversationId:'default',text:'只读邮件标题'});}
function finish(h:ReturnType<typeof fixture>){h.event({kind:'text_delta',delta:raw});h.event({kind:'agent_end'});}
it('an acknowledgement alone still requires one result delivery',async()=>{const h=fixture();try{await start(h);const runId=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'ack-only',runId,kind:'ack',text:'收到，我先看标题。',composedAt:100,status:'composed'}});finish(h);expect(h.compose).toHaveBeenCalledTimes(1);h.resolve('竹海工作坊发来了活动邀请，目前仅读标题。');await vi.waitFor(()=>expect(h.messages.some(m=>m.event?.kind==='user_delivery'&&m.event.delivery.kind==='finding')).toBe(true));h.event({kind:'agent_end'});expect(h.compose).toHaveBeenCalledTimes(1);}finally{h.manager.dispose();}});
it('a failed run cannot receive a late successful makeup answer',async()=>{const h=fixture();try{await start(h);finish(h);expect(h.compose).toHaveBeenCalledTimes(1);h.event({kind:'error',message:'任务读取失败'});h.resolve('找到活动邀请。');await new Promise(r=>setTimeout(r,10));expect(h.messages.filter(m=>m.event?.kind==='user_delivery'&&m.event.delivery.kind==='finding')).toHaveLength(0);expect(h.manager.getTaskProgress('default')!.state).toBe('error');}finally{h.manager.dispose();}});
it('a prior follow-up delivery cannot be retagged onto a later text run',async()=>{const h=fixture();try{await start(h);const old=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'old-finding',runId:old,kind:'finding',text:raw,composedAt:100,status:'composed'}});finish(h);const result:any=await h.manager.routeVoiceInput('default','活动那个呢？',null,()=>true,{requestId:'query-one',voiceId:'voice-one',turn:1,runId:old});expect(result.awaitDelivery).toBe(true);const followupRun=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'followup-one',runId:followupRun,kind:'finding',text:raw,composedAt:101,status:'composed'}});finish(h);await h.manager.handleMessage({type:'user_message',conversationId:'default',text:'新的地图任务'});const current=h.manager.getTaskProgress('default')!.runId!;expect(current).not.toBe(followupRun);h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'late-followup',runId:followupRun,kind:'reply',text:raw,composedAt:102,status:'composed'}});expect(h.manager.getTaskProgress('default')!.conversationContext?.latestDelivery??null).toBeNull();}finally{h.manager.dispose();}});

it('an idle page question waits for a formal result from the execution session',async()=>{const h=fixture('observe');try{await h.manager.ensureDefault();const result:any=await h.manager.routeVoiceInput('default','看看活动那封',null,()=>true,{requestId:'observe-one',voiceId:'voice-one',turn:1,runId:null,input:{observation:{token:'token-one',tabId:1}}});expect(result).toMatchObject({kind:'action',ok:true,awaitDelivery:true});const runId=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'observation-finding',runId,kind:'finding',text:raw,composedAt:100,status:'composed'}});finish(h);expect(h.manager.getTaskProgress('default')!.conversationContext?.latestDelivery?.id).toBe('observation-finding');expect(h.compose).not.toHaveBeenCalled();}finally{h.manager.dispose();}});
it('an idle follow-up playback updates its own execution delivery',async()=>{const h=fixture();try{await start(h);const old=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'original-finding',runId:old,kind:'finding',text:raw,composedAt:100,status:'composed'}});finish(h);const result:any=await h.manager.routeVoiceInput('default','活动那个呢？',null,()=>true,{requestId:'reply-playback',voiceId:'voice-one',turn:1,runId:old});expect(result.awaitDelivery).toBe(true);const runId=h.manager.getTaskProgress('default')!.runId!;h.event({kind:'user_delivery',delivery:{conversationId:'default',id:'new-answer',runId,kind:'finding',text:raw,composedAt:101,status:'composed'}});finish(h);h.manager.markDeliveryPlayback('default','new-answer','played');expect(h.manager.getTaskProgress('default')!.conversationContext?.latestDelivery).toMatchObject({id:'new-answer',status:'played'});}finally{h.manager.dispose();}});
