// Boss-owned ledger contract; implementers must not edit.
import {it,expect} from 'vitest';
import {UserDeliveryLedger} from '../src/user-delivery-ledger.js';
import type {UserDelivery} from '../../shared/voice.js';
const record=(extra:Partial<UserDelivery>={}):UserDelivery=>({conversationId:'default',id:'delivery-a',runId:'run-a',kind:'finding',text:'已查看竹海活动标题，尚未打开正文。',composedAt:100,status:'composed',...extra});
it('ack cannot clear the result obligation or replace a later finding',()=>{const l=new UserDeliveryLedger('default');l.beginRun('run-a');expect(l.record(record({id:'ack-first',kind:'ack'}))).toBe(true);expect(l.hasFinding()).toBe(false);l.record(record());expect(l.hasFinding()).toBe(true);l.record(record({id:'ack-late',kind:'ack',composedAt:200}));expect(l.latest()?.id).toBe('delivery-a');expect(l.hasFinding()).toBe(true);});
it('one delivery id cannot be reused to change text',()=>{const l=new UserDeliveryLedger('default');l.beginRun('run-a');expect(l.record(record())).toBe(true);expect(l.record(record())).toBe(false);expect(l.record(record({text:'正文已读完'}))).toBe(false);expect(l.latest()?.text).toBe(record().text);});
it('playback updates cannot invent, regress or replace a newer answer',()=>{const l=new UserDeliveryLedger('default');l.beginRun('run-a');expect(l.markPlayback('unknown','played')).toBeNull();l.record(record());l.markPlayback('delivery-a','played');l.markPlayback('delivery-a','speaking');expect(l.latest()?.status).toBe('played');l.record(record({id:'reply-b',kind:'reply',composedAt:200}));l.markPlayback('delivery-a','played');expect(l.latest()?.id).toBe('reply-b');});
it('returned records are detached from callers and a new run excludes old deliveries',()=>{const l=new UserDeliveryLedger('default');l.beginRun('run-a');const d=record();l.record(d);d.text='mutated input';const copy=l.latest()!;copy.text='mutated snapshot';expect(l.latest()?.text).toBe(record().text);l.beginRun('run-b');expect(l.hasFinding()).toBe(false);expect(l.record(record())).toBe(false);expect(l.markPlayback('delivery-a','played')).toBeNull();expect(l.latest()).toBeNull();});
it('null-run chat can be recorded without masquerading as task findings',()=>{const l=new UserDeliveryLedger('default');l.beginRun(null);expect(l.record(record({runId:null,kind:'reply'}))).toBe(true);expect(l.hasFinding()).toBe(false);expect(l.record(record({id:'foreign',runId:null,conversationId:'other'}))).toBe(false);});
