import {resolve} from 'node:path';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {launchIsolatedExtension,until} from './isolated-extension.mts';

if (!process.argv.includes('--headless')) throw new Error('Required --headless');
let commits=0,uploadEvents=0;
const iso=await launchIsolatedExtension({localOnly:true,fixtureHtml:'<!doctype html><title>Security fixture</title><form><input id="email" value="first"><button id="commit" type="button" onclick="fetch(\'/commit\',{method:\'POST\'})">Continue</button></form>',fixture:(req,res)=>{if(req.url==='/upload-event'){uploadEvents++;res.end('ok');return true;}if(req.url?.startsWith('/child')){res.setHeader('Content-Type','text/html');res.end('<input id=child-name value=before>');return true;}if(req.url==='/commit'){commits++;res.end('ok');return true;}return false;}});
const evidence:any[]=[];
let panel="";
await mkdir("out/security-confirmation",{recursive:true});
try {
  const extensionId=await iso.swEval('chrome.runtime.id');
  const page=await iso.newTarget(iso.fixtureOrigin);
  panel=await iso.newTarget('chrome-extension://'+extensionId+'/sidepanel.html');
  await iso.swEval('globalThis.__saSetSecurityHost({id:"default",title:"Security fixture",createdAt:1,updatedAt:1,state:"running",mode:"act",runId:"security-run"})');
  await until(async()=>{const state=await iso.swEval('globalThis.__saSecurityProbe()') as any;return state.panels>0&&state.summaries?.some((c:any)=>c.id==='default'&&c.runId==='security-run')?true:undefined;},8000,'trusted panel attached and fixture run active');
  const tabId=await iso.swEval('(async()=> (await chrome.tabs.query({url:'+JSON.stringify(iso.fixtureOrigin+'/*')+'}))[0].id)()');
  let seq=0;
  const start=async(name:string,params:any)=>{
    await iso.swEval('globalThis.__securityResult=globalThis.__saCall('+JSON.stringify('security-'+ ++seq)+','+JSON.stringify(name)+','+JSON.stringify(params)+',"acpt",undefined,"default",{runId:"security-run"});globalThis.__securitySettled=null;void globalThis.__securityResult.then(r=>globalThis.__securitySettled=r,e=>globalThis.__securitySettled={error:String(e)});true');
  };
  const card=async()=>until(()=>iso.evalIn(panel,'document.querySelector(".consent-card:not(.consent-complete) .consent-allow:not(:disabled)") ? true : undefined'),8000,'real sidebar consent card');
  const result=()=>iso.swEval('globalThis.__securityResult');
  const oracle=async(expected:number)=>{await until(()=>commits===expected?true:undefined,4000,'fixture commit count');assert.equal(commits,expected);};
  await start('snapshot',{tabId});await card();await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).ok,true);await oracle(0);
  await start('click',{tabId,target:'#commit',label:'Read only',fromUserConfirm:true});
  await card();await oracle(0);await iso.clickButton(panel,'拒绝');assert.equal((await result() as any).executionFact,'not_executed');await oracle(0);evidence.push({case:'forged confirmation and harmless label denied',commits});
  await start('click',{tabId,target:'#commit'});await card();await oracle(0);await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).ok,true);await oracle(1);evidence.push({case:'trusted sidebar allows exactly one',commits});
  await start('click',{tabId,target:'#commit'});await card();await oracle(1);await iso.clickButton(panel,'拒绝');await result();await oracle(1);evidence.push({case:'second click needs fresh permission',commits});
  await start('click',{tabId,target:'#commit'});await card();
  await iso.evalIn(page,'document.querySelector("#commit").replaceWith(document.querySelector("#commit").cloneNode(true))');
  await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'identical target replacement invalidates approval',commits});
  await start('click',{tabId,target:'#commit'});await card();
  await iso.evalIn(page,'document.querySelector("#commit").setAttribute("onclick", "fetch(\'/commit\',{method:\'POST\'})");document.querySelector("#commit").setAttribute("data-changed","true")');
  await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'same text attribute mutation invalidates approval',commits});
  await iso.evalIn(page,'(()=>{const host=document.createElement("div");host.id="shadow-host";host.attachShadow({mode:"open"}).innerHTML="<button id=shadow-commit>Continue</button>";document.body.append(host);})()');
  await start('click',{tabId,target:'#shadow-commit'});await card();
  await iso.evalIn(page,'(()=>{const root=document.querySelector("#shadow-host").shadowRoot;root.querySelector("button").replaceWith(root.querySelector("button").cloneNode(true));})()');
  await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'native backend identity binds same-text shadow target',commits});
  await iso.evalIn(page,'(()=>{const frame=document.createElement("iframe");frame.id="child";frame.src="/child";document.body.append(frame);})()');
  await until(()=>iso.evalIn(page,'Boolean(document.querySelector("#child").contentDocument?.querySelector("#child-name"))'),5000,'same-origin child ready');
  await start('js',{tabId,code:'fetch("/commit",{method:"POST"})'});await card();
  await iso.evalIn(page,'document.querySelector("#child").contentDocument.querySelector("#child-name").value="changed"');
  await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'native child field value invalidates approval',commits});
  await start('js',{tabId,code:'fetch("/commit",{method:"POST"})'});await card();
  await iso.evalIn(page,'document.querySelector("#child").contentWindow.location.replace("/child?next")');
  await until(()=>iso.evalIn(page,'document.querySelector("#child").contentWindow.location.search==="?next"'),5000,'child navigation');
  await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'child navigation invalidates approval',commits});
  await start('js',{tabId,code:'fetch("/commit",{method:"POST"})'});await card();await oracle(1);
  await iso.evalIn(page,'document.querySelector("#email").value="changed"');await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(1);evidence.push({case:'form mutation invalidates JS approval',commits});
  await start('js',{tabId,code:'fetch("/commit",{method:"POST"})'});await card();await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).ok,true);await oracle(2);evidence.push({case:'explicitly approved JS may post exactly once',commits});
  await start('js',{tabId,code:'"email\\n" + document.querySelector("#email").value'});await card();await iso.clickButton(panel,'允许一次');
  const csv=await result() as any;assert.equal(csv.ok,true);assert.equal(csv.data.value,'email\nchanged');await oracle(2);evidence.push({case:'approved CSV extraction retains complete data',commits});
  const uploadPath=resolve('out/security-confirmation/upload.txt');await writeFile(uploadPath,'approved fixture upload');
  await iso.evalIn(page,'(()=>{const input=document.createElement("input");input.type="file";input.id="upload";input.onchange=()=>fetch("/upload-event",{method:"POST"});document.body.append(input);})()');
  await start('upload_file',{tabId,target:'#upload',paths:[uploadPath]});await card();await iso.clickButton(panel,'允许一次');
  const uploaded=await result() as any;assert.equal(uploaded.ok,true);await until(()=>uploadEvents===1?true:undefined,4000,'approved upload change event');
  assert.equal(await iso.evalIn(page,'document.querySelector("#upload").files[0].name'),'upload.txt');await oracle(2);evidence.push({case:'approved upload completes value and one change event',uploadEvents,commits});
  const keyboard=await iso.tool('press_key',{tabId,key:'Enter'});assert.equal(keyboard.executionFact,'not_executed');
  const cdp=await iso.tool('cdp',{tabId,method:'Input.dispatchKeyEvent',params:{type:'keyDown',key:'Enter'}});assert.equal(cdp.executionFact,'not_executed');await oracle(2);
  await start('click',{tabId,target:'#commit'});await card();await iso.evalIn(page,'location.reload()');await new Promise(resolve=>setTimeout(resolve,500));await iso.clickButton(panel,'允许一次');assert.equal((await result() as any).executionFact,'not_executed');await oracle(2);evidence.push({case:'reload invalidates old approval',commits});
  await mkdir('out/security-confirmation',{recursive:true});await iso.screenshot(panel,'out/security-confirmation/sidebar.png');await writeFile('out/security-confirmation/result.json',JSON.stringify({status:'PASS',evidence},null,2));
} catch(error) {
  const diagnostics={error:String(error),evidence,tool:await iso.swEval('globalThis.__securitySettled'),background:await iso.swEval('globalThis.__saSecurityProbe()'),panel:panel?await iso.evalIn(panel,'document.body.innerText'):null};
  await writeFile('out/security-confirmation/failure.json',JSON.stringify(diagnostics,null,2));
  if(panel)await iso.screenshot(panel,'out/security-confirmation/failure.png').catch(()=>{});
  console.error(JSON.stringify(diagnostics));throw error;
} finally {await iso.close();}
