/** Leaves a controlled fixture to the human; does not start voice or operate it after setup. */
import {createServer} from 'node:http';
import {NativeVoiceHarness} from './native-voice-harness.mts';
const server=createServer((_q,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="zh"><meta charset="utf-8"><title>语音人工测试 · 商品筛选</title><style>body{font:18px system-ui;max-width:800px;margin:64px auto;padding:0 24px;color:#252525;background:#faf9f6}h1{font-size:30px}label{display:block;margin:24px 0 10px}input,select,button{font:inherit;padding:10px;border:1px solid #bbb;border-radius:6px}button{margin:20px 0;background:#fff;cursor:pointer}li{padding:10px}small{color:#666}#marker{width:85%}</style><h1>商品筛选</h1><p>让语音助手操作这张页面，直接看结果。</p><label for="budget">最高预算</label><input id="budget" type="number" value="1000"><label for="sort">排序</label><select id="sort"><option value="original">原始顺序</option><option value="asc">价格从低到高</option></select><br><button id="apply">筛选一次</button><p>筛选次数：<b id="count">0</b></p><ol id="result"></ol><label for="marker">人工标记（暂停后由你修改）</label><input id="marker" value="还没有手动改动"><p><small>每次点击筛选只执行一次。页面没有自动计时器。</small></p><script>document.querySelector('#apply').onclick=()=>{const budget=Number(document.querySelector('#budget').value);let prices=[899,699,1099,799].filter(n=>n<=budget);if(document.querySelector('#sort').value==='asc')prices.sort((a,b)=>a-b);document.querySelector('#result').innerHTML=prices.map(p=>'<li>书桌 · ¥'+p+'</li>').join('');const counter=document.querySelector('#count');counter.textContent=String(Number(counter.textContent)+1);};</script></html>`);});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${(server.address() as any).port}/`;
const h=await NativeVoiceHarness.open('voice-human');const id=await h.create('人工语音测试 · 商品筛选');const tab=await h.openTab(id,url);
await h.p(`testPort.postMessage(${JSON.stringify({kind:'select_conversation',conversationId:id})})`);
await h.finishReport({phase:'awaiting-human',conversationId:id,tabId:tab.tabId,url,source:'real human microphone; no injected audio or task'});
console.log(JSON.stringify({out:h.out,conversationId:id,tabId:tab.tabId,url}));
let closing=false;const close=async()=>{if(closing)return;closing=true;await h.close();server.closeAllConnections();server.close();process.exit(0);};process.on('SIGINT',close);process.on('SIGTERM',close);
